version: '3.7'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schoolsphere
    image: schoolsphere:latest
    command: yarn start:dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:ttX1d3svmiR4ZxADMzd6sYq3pQZY95Tf@dpg-ck0grk9au56s73ddmud0-a.oregon-postgres.render.com/schoolsphere
      #  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/app
      - /app/node_modules
